"""Agregar tabla justificativo

Revision ID: 5278ee63d599
Revises: 88abaf8c5647
Create Date: 2026-02-09 10:44:10.453809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5278ee63d599'
down_revision = '88abaf8c5647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('justificativo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('fecha_clase', sa.String(length=20), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('archivo_nombre', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('career')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ci')
        batch_op.drop_column('segundo_apellido')
        batch_op.drop_column('segundo_nombre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('segundo_nombre', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('segundo_apellido', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('ci', sa.VARCHAR(length=20), nullable=True))

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('career', sa.TEXT(), nullable=True))

    op.drop_table('justificativo')
    # ### end Alembic commands ###
