"""Agregar modelos HistorialAsistencia y DetalleAsistencia

Revision ID: 5443b53f0380
Revises: b3d061c3ee5a
Create Date: 2026-02-09 12:45:22.738850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5443b53f0380'
down_revision = 'b3d061c3ee5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('codigo_sesion', sa.String(length=20), nullable=False),
    sa.Column('total_alumnos', sa.Integer(), nullable=True),
    sa.Column('total_presentes', sa.Integer(), nullable=True),
    sa.Column('total_justificados', sa.Integer(), nullable=True),
    sa.Column('total_ausentes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('historial_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['historial_id'], ['historial_asistencia.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_asistencia')
    op.drop_table('historial_asistencia')
    # ### end Alembic commands ###
