"""Cambiar cedula por ci

Revision ID: b3d061c3ee5a
Revises: f338b0212ddd
Create Date: 2026-02-09 11:26:11.064884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d061c3ee5a'
down_revision = 'f338b0212ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ci', sa.String(length=20), nullable=True))
        batch_op.drop_column('cedula')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cedula', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('ci')

    # ### end Alembic commands ###
