"""Agregar campo cedula a User

Revision ID: f338b0212ddd
Revises: 5278ee63d599
Create Date: 2026-02-09 11:24:24.935196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f338b0212ddd'
down_revision = '5278ee63d599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cedula', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cedula')

    # ### end Alembic commands ###
